# This file contains the fastlane.tools configuration # You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
   desc "AirCastingApp"

   # before_all do |lane|
   #    tests
   # end

   lane :beta do
      ensure_git_branch(branch: "develop")
      ensure_git_status_clean
      increment_build_number
      version = get_version_number
      build = get_build_number
      begin
         cocoapods

         add_badge
         output_dir = "./build_ipa/#{version}b#{build}(BT)"
         build_app(workspace: "AirCasting.xcworkspace", scheme: "AirCasting", export_method: "ad-hoc", silent: "true", output_directory: output_dir, configuration: "Beta")
         firebase_app_distribution(
            app: "1:51291628191:ios:b090a81539b7acbb48b8aa",
            groups: "always_testers",
            release_notes: "Beta #{version}"
         )
         upload_symbols_to_crashlytics(dsym_path: "#{output_dir}/AirCasting.app.dSYM.zip",
                                       gsp_path: "./GoogleService-Info.plist",
                                       app_id: "1:51291628191:ios:b090a81539b7acbb48b8aa",
                                       binary_path: "./upload-symbols")
         reset_git_repo(files: "AirCasting/Assets.xcassets/*")
         sh("git checkout -b beta/#{version}b#{build}")
         git_add
         git_commit(path: "", message: "Beta releasae of #{version}b#{build}")
      rescue => ex
         reset_git_repo(skip_clean: true)
         raise
      end
   end

   lane :release_update do
      ensure_git_status_clean
      version = get_version_number
      ensure_git_branch(branch: "release/#{version}")
      increment_build_number
      build = get_build_number
      begin
         test_flight
         build_app(workspace: "AirCasting.xcworkspace", scheme: "AirCasting", export_method: "ad-hoc", silent: "true", output_directory: "./build_ipa/#{version}b#{build}(RC)", configuration: "Release", export_options: {
            provisioningProfiles: {
               "org.habitatmap.AirCasting": "AirCasting Ad hoc distribution"
            }
         })
         firebase_app_distribution(
            app: "1:51291628191:ios:b090a81539b7acbb48b8aa",
            groups: "always_testers",
            release_notes: "Release Candidate #{version} build #{build}"
         )
         download_dsyms(app_identifier: "org.habitatmap.AirCasting", version: version, build_number: build, api_key: get_appstore_api_key)
         upload_symbols_to_crashlytics(gsp_path: "./GoogleService-Info.plist",
                                       app_id: "1:51291628191:ios:b090a81539b7acbb48b8aa",
                                       binary_path: "./upload-symbols")
         sh("git add -A")
         sh("git commit -m \"RC version #{version} build #{build}\"")
         sh("git push -u origin release/#{version}")
      rescue => ex
         reset_git_repo(skip_clean: true)
         raise
      end
   end

   lane :hotfix_init do
      ensure_git_status_clean
      ensure_git_branch(branch: "main")
      increment_version_number(bump_type: "patch")
      version = get_version_number
      sh("git checkout -b hotfix/#{version}")
      sh("git add -A")
      sh("git commit -m \"Change version number to #{version}\"")
      sh("git push -u origin hotfix/#{version}")
   end

   lane :hotfix_release do
      ensure_git_status_clean
      version = get_version_number
      build = get_build_number
      ensure_git_branch(branch: "hotfix/#{version}")
      begin
         test_flight
         build_app(workspace: "AirCasting.xcworkspace", scheme: "AirCasting", export_method: "ad-hoc", silent: "true", output_directory: "./build_ipa/#{version}b#{build}(HF)", configuration: "Release", export_options: {
            provisioningProfiles: {
               "org.habitatmap.AirCasting": "AirCasting Ad hoc distribution"
            }
         })
         firebase_app_distribution(
            app: "1:51291628191:ios:b090a81539b7acbb48b8aa",
            groups: "always_testers",
            release_notes: "Hotfix #{version} build #{build}"
         )
         download_dsyms(app_identifier: "org.habitatmap.AirCasting", version: version, build_number: build, api_key: get_appstore_api_key)
         upload_symbols_to_crashlytics(gsp_path: "./GoogleService-Info.plist", 
                                       app_id: "1:51291628191:ios:b090a81539b7acbb48b8aa", 
                                       binary_path: "./upload-symbols")
      end
   end

   lane :release do
      ensure_git_status_clean
      version = get_version_number
      ensure_git_branch(branch: "develop")
      build = get_build_number
      begin
         test_flight
         build_app(workspace: "AirCasting.xcworkspace", scheme: "AirCasting", export_method: "ad-hoc", silent: "true", output_directory: "./build_ipa/#{version}b#{build}(RC)", configuration: "Release", export_options: {
            provisioningProfiles: {
               "org.habitatmap.AirCasting": "AirCasting Ad hoc distribution"
            }
         })
         firebase_app_distribution(
            app: "1:51291628191:ios:b090a81539b7acbb48b8aa",
            groups: "always_testers",
            release_notes: "Release Candidate #{version} build #{build}"
         )
         download_dsyms(app_identifier: "org.habitatmap.AirCasting", version: version, build_number: build, api_key: get_appstore_api_key)
         upload_symbols_to_crashlytics(gsp_path: "./GoogleService-Info.plist",
                                       app_id: "1:51291628191:ios:b090a81539b7acbb48b8aa",
                                       binary_path: "./upload-symbols")
         sh("git checkout -b release/#{version}")
         sh("git push -u origin release/#{version}")
      rescue => ex
         reset_git_repo(skip_clean: true)
         raise
      end
   end

   lane :tests do
      run_tests(scheme: "AirCasting")
    end

   lane :bump_version_reset_build do
      ensure_git_branch(branch: "develop")
      ensure_git_status_clean
      current_version = get_version_number
      puts "Current version number: #{current_version}"
      new_version = prompt(text: "Please enter a new version number: ")
      increment_version_number_in_xcodeproj(
         version_number: new_version
      )
      increment_build_number(
         build_number: "0"
      )
      puts "Setting a version number to #{new_version} and reseting build to #{get_build_number}"
      sh("git checkout -b bumped_version_to_#{new_version}")
      sh("git add -A")
      sh("git commit -m \"Change version number to #{new_version} and build reset\"")
      sh("git push -u origin bumped_version_to_#{new_version}")
   end

   private_lane :test_flight do
      cocoapods
      build_app(workspace: "AirCasting.xcworkspace", scheme: "AirCasting", export_method: "app-store", output_directory: "./build_ipa/testflight", configuration: "Release")
      upload_to_testflight(
         api_key: get_appstore_api_key
      )
      clean_build_artifacts
   end

   private_lane :get_appstore_api_key do
      app_store_connect_api_key(
         key_id: ENV["APPSTORE_KEY_ID"],
         issuer_id: ENV["APPSTORE_ISSUER_ID"],
         key_filepath: "fastlane/AuthKey.p8",
         in_house: false
      )
   end
end
